import { Inter } from 'next/font/google'
import './globals.css'
import Header from './header'
import Footer from './footer'
import Image from 'next/image'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'evengreener',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} >
        <div className='wrapper-div'>
          <div className="bannerinner">
            <h3>Text to display</h3>
          </div>
          <div className='main-header-section'>
             <div className='logo-div'>
               <Image src="/icons/tiktok.svg" alt='tiktok' width={25} height={25}/>
               <Image src="/icons/youtube.svg" alt='youtube' width={25} height={25}/>
               <Image src="/icons/instagram.svg" alt='instagram' width={25} height={25}/>
               <Image src="/icons/facebook.svg" alt='facebook' width={25} height={25}/>
               <Image src="/icons/pinterest.svg" alt='pinterest' width={25} height={25}/>
            </div>
            <div>
              <Image src="/images/evengreener-logo.avif" alt='logo' width={80} height={80}/>
            </div>
            <div>
              <Image src="icons/search.svg" alt='search' width={25} height={25} />
              <Image src="icons/likes.svg" alt='likes' width={25} height={25} />
              <Image src="icons/user.svg" alt='user' width={25} height={25} />
              <Image src="icons/cart.svg" alt='cart' width={25} height={25} />
            </div>
          </div>
          <div className='menu-bar'>
            <Header />
          </div>
          {children}
        <Footer />
        </div>     
      </body>
    </html>
  )
}
